function MovePlayerPaddle
        %Reading mouse movement
        currentmousepos = myPos;
        mousespeed=currentmousepos(2)-lastmousepos(2);
        %Moving paddle
        playerpaddlepos(2)=playerpaddlepos(2)+...
                           playerpaddlespeed+...
                           (mousespeed*fieldwidth/(0.8*windowsize(2)));
        %Preventing paddle to go off field
        if playerpaddlepos(2)>=0.5*(fieldwidth-playerpaddlelength)
            playerpaddlepos(2)=0.5*(fieldwidth-playerpaddlelength);
        elseif playerpaddlepos(2)<=-0.5*(fieldwidth-playerpaddlelength)
            playerpaddlepos(2)=-0.5*(fieldwidth-playerpaddlelength);
        end
        playerpaddlexdat=[playerpaddlepos(1)-0.5*playerpaddlethickness,...
                          playerpaddlepos(1)+0.5*playerpaddlethickness,...
                          playerpaddlepos(1)+0.5*playerpaddlethickness,...
                          playerpaddlepos(1)-0.5*playerpaddlethickness];
        playerpaddleydat=[playerpaddlepos(2)-0.5*playerpaddlelength,...
                          playerpaddlepos(2)-0.5*playerpaddlelength,...
                          playerpaddlepos(2)+0.5*playerpaddlelength,...
                          playerpaddlepos(2)+0.5*playerpaddlelength];
%         set(0,'PointerLocation',[centermousepos(1),...
%                                  centermousepos(2)+...
%                                  0.8*windowsize(2)*playerpaddlepos(2)/...
%                                  fieldwidth])
        %Saving cursor last position
        lastmousepos(2)=centermousepos(2)+(0.8*windowsize(2)*...
                                           playerpaddlepos(2)/...
                                           fieldwidth);
    end